In [3]:
# Part 1: Theoretical Questions

# Q1: What are the different data structures used in TensorFlow? Give some examples.

# TensorFlow primarily uses two data structures: tensors and graphs. Tensors are multi-dimensional arrays that represent data, and they can have different ranks (0D, 1D, 2D, etc.). Examples include scalars, vectors, and matrices. Graphs represent the computation and the flow of tensors between operations.

# Q2: How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

# TensorFlow constants are tensors with fixed values that do not change during the execution of a graph. They are used for values that remain constant throughout the computation. For example:

import tensorflow as tf
constant_value = tf.constant(5.0)  # Creates a constant tensor with value 5.0
# TensorFlow variables, on the other hand, are tensors that can be updated and modified during training. They are typically used to store model parameters that need to be learned. For example:

import tensorflow as tf
variable_value = tf.Variable(0.0)  # Creates a variable tensor with an initial value of 0.0

# Part 2: Practical Implementation

# Task 1: Creating and Manipulating Matrices

import tensorflow as tf

# Create a normal matrix A with dimensions 2x2
matrix_A = tf.random.normal(shape=(2, 2))
print("Matrix A:\n", matrix_A.numpy())

# Create a Gaussian matrix B with dimensions 2x2
matrix_B = tf.random.truncated_normal(shape=(2, 2))
print("Matrix B:\n", matrix_B.numpy())

# Create a matrix C with dimensions 2x2 with a custom normal distribution
mean = 2.0
stddev = 0.1
matrix_C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print("Matrix C:\n", matrix_C.numpy())

# Perform matrix addition between matrix A and matrix B
matrix_D = matrix_A + matrix_B
print("Matrix D (A + B):\n", matrix_D.numpy())

# Perform matrix multiplication between matrix C and matrix D
matrix_E = tf.matmul(matrix_C, matrix_D)
print("Matrix E (C * D):\n", matrix_E.numpy())

# Task 2: Performing Additional Matrix Operations

# Create a matrix F with dimensions 2x2 using random_uniform
matrix_F = tf.random.uniform(shape=(2, 2))
print("Matrix F:\n", matrix_F.numpy())

# Calculate the transpose of matrix F
matrix_G = tf.transpose(matrix_F)
print("Matrix G (Transpose of F):\n", matrix_G.numpy())

# Calculate the element-wise exponential of matrix F
matrix_H = tf.exp(matrix_F)
print("Matrix H (Exp of F):\n", matrix_H.numpy())

# Create a matrix I by concatenating matrix F and matrix G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)
print("Matrix I (Horizontal Concatenation of F and G):\n", matrix_I.numpy())

# Create a matrix J by concatenating matrix F and matrix H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)
print("Matrix J (Vertical Concatenation of F and H):\n", matrix_J.numpy())
# This code demonstrates creating and manipulating matrices using TensorFlow operations. It includes tasks such as creating random matrices, performing matrix addition and multiplication, calculating transposes, and concatenating matrices horizontally and vertically.

2023-09-30 14:21:58.634249: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-30 14:21:59.134007: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-09-30 14:21:59.134068: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-09-30 14:21:59.137399: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-09-30 14:21:59.417022: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-30 14:21:59.420074: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

Matrix A:
 [[1.0964041  0.5151317 ]
 [0.3779863  0.36239055]]
Matrix B:
 [[-0.7409414  -0.9519592 ]
 [ 1.0912178  -0.30854854]]
Matrix C:
 [[2.0253778 2.0301013]
 [2.037011  1.9953821]]
Matrix D (A + B):
 [[ 0.35546267 -0.43682748]
 [ 1.4692041   0.05384201]]
Matrix E (C * D):
 [[ 3.7025793 -0.7754359]
 [ 3.6557047 -0.782387 ]]
Matrix F:
 [[0.60738754 0.15729642]
 [0.17649066 0.5303093 ]]
Matrix G (Transpose of F):
 [[0.60738754 0.17649066]
 [0.15729642 0.5303093 ]]
Matrix H (Exp of F):
 [[1.8356296 1.1703424]
 [1.1930233 1.6994579]]
Matrix I (Horizontal Concatenation of F and G):
 [[0.60738754 0.15729642 0.60738754 0.17649066]
 [0.17649066 0.5303093  0.15729642 0.5303093 ]]
Matrix J (Vertical Concatenation of F and H):
 [[0.60738754 0.15729642]
 [0.17649066 0.5303093 ]
 [1.8356296  1.1703424 ]
 [1.1930233  1.6994579 ]]
